### ISSUE TITLE
allow .makeRandomCreature to create a user-defined number of creatures per run

### ISSUE THREAD

**Issue by Zombpossum** [A554551N/chorumfur-bot#50]
Make loop to .createRandomCreature

**Comment by A554551N** [comment]
Implemented enhancement in new branch.  Code will no longer accept a name parameter, but instead will accept an optional quantity parameter that will determine how many times the interior loop runs (defaults to once).

For this fix I'm attempting an async for loop to prevent the creation from blocking the Bot process, unsure if it will be successful in that regard.
